### PR TITLE
RENO-1705: Remove title attribute from svg element due to HTML validation

### PR DESCRIPTION
**Pull request by misselbeck**
[Jira Ticket](http://jira.nypl.org/browse/RENO-1705)

**This PR does the following:**
- Removes the title attribute from the svg element on the social icons

**Reason:**
The title attribute causes any app using the social icon (such as the footer), to fail HTML validation. According [to this doc](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/title), the <title> element inside the svg element is sufficient for A11y, as well as providing the hover tooltip to user. The attribute is not needed.

### CODE REVIEW

**Comment by EdwinGuzman** [comment]
Looks good. Can you update the changelog and the version in package.json to deploy this to npm?

**Comment by misselbeck** [comment]
Thanks, Edwin. CHANGELOG updated, as noted.

**Review by EdwinGuzman — APPROVED** [review]

**Comment by EdwinGuzman** [comment]
I'm going to go ahead and merge and deploy a new version if that's okay @gkallenberg ?

**Comment by EdwinGuzman** [comment]
@misselbeck I just published the new version on npm so it's ready to use!

**Pull request merged**
